apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: sashapo12/project:9
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: my-mongodb-release.default.svc.cluster.local
        - name: MONGO_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongodb-root-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongodb-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: app
  type: NodePort
